---
- name: "Docker Image Build From Github Push Event"
  hosts: build
  become: true
  vars:
    repo_url: "https://github.com/Freeda-F/FlaskApp-demo.git"
    repo_dest: "/var/repository"
    image_name: "freedafrancis/flaskapp-demo"
    docker_username: "freedafrancis"
    docker_password: "*****"
  tasks:

    - name: "Build-Setp - Docker Installation"
      shell: 'amazon-linux-extras install docker -y'
      args:
       warn: no

    - name: "Build-Step - Additional package Installation"
      yum:
        name: git,python-pip
        state: present


    - name: "Build-Step - python docker extension installation"
      pip:
        name: docker-py

    - name: "Build-Step - Docker service restart/enable"
      service:
        name: docker
        state: restarted
        enabled: true

    - name: "Build-Step - Cloning Repository"
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
      register: repo_status

    - name: "Build-Step - Login to remote Repository"
      when: repo_status.changed == true
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: "Build-Step - Building image"
      when: repo_status.changed == true
      docker_image:
        source: build
        build:
          path: "{{ repo_dest }}"
          pull: yes
        name: "{{ image_name }}"
        tag: "{{ item }}"
        push: true
        force_tag: yes
        force_source: yes
      with_items:
        - "{{ repo_status.after }}"
        - latest


    - name: "Build-Step - removing image"
      when: repo_status.changed == true
      docker_image:
        state: absent
        name: "{{ image_name }}"
        tag: "{{ item }}"
      with_items:
        - "{{ repo_status.after }}"
        - latest

- name: "Docker Run Container"
  hosts: test
  become: true
  vars:
    image_name: "freedafrancis/flaskapp-demo"

  tasks:

    - name: "Deployment - Docker Installation"
      shell: 'amazon-linux-extras install docker -y'
      args:
        warn: no

    - name: "Deployment - Additional package Installation"
      yum:
        name: python-pip
        state: present

    - name: "Deployment - python docker extension installation"
      pip:
        name: docker-py

    - name: "Deployment - Docker service restart/enable"
      service:
        name: docker
        state: restarted
        enabled: true

    - name: "Deployment - Run Container"
      docker_container:
        name: webserver
        image: "{{ image_name }}:latest"
        recreate: yes
        pull: yes
        published_ports:
          - "80:5000"
